### PR TITLE
added initial readme defining various parts of the project, it should…

### LINKED ISSUE #4: ReadMe with all project info

### PR DESCRIPTION
**Pull request by steveo9219**
… be updated as the project goes on

### CODE REVIEW

**Comment by steveo9219** [comment]
if anyone wants me to add or change anything let me know

**Review by chong0810 — APPROVED** [review]
Looks good!

**Review by CGMcBride — APPROVED** [review]

**Review by dianecandler — DISMISSED** [review]
Please add 1) customer requirements document (Teams) 2) XD (Teams) and updated wireframes with explained progression  3) remove dupe of reference links 4) add flow charts 5) add Adobe XD and Draw.io plus Teams, Slack, and technologies  - could break these out and list dependencies separate and list Express, Concurrently, etc.  May add Postman, GitHub, Heroku, Zoom, Meet.Google, etc.  Maybe we can all help brainstorm this list? 6) meeting notes link .  If you don't add content, at least add placeholders so this is managed before we complete the project.

**Review by vlt44 — COMMENTED** [review]
Approved! Great starting draft and point to build on.

**Review by vlt44 — APPROVED** [review]
Let's starting considering edits and additional resources to upload. Continue to keep this card open for the working session for 9-18.

**Pull request merged**
